### ISSUE TITLE
thirdparty中import错误

### ISSUE THREAD

**Issue by JaySon-Huang** [fooying/3102#34]
我的机器系统第三方库中没有安装`gevent`,会提示这样的错误：

```
No module named gevent.hub
Traceback (most recent call last):
  File "run3102.py", line 17, in main
    from core.parser import parse
  File "/Users/JaySon/PythonProjects/3102/core/parser.py", line 14, in <module>
    from core.controllers.plugin_controller import PluginController
  File "/Users/JaySon/PythonProjects/3102/core/controllers/plugin_controller.py", line 13, in <module>
    from thirdparty import gevent
  File "/Users/JaySon/PythonProjects/3102/thirdparty/gevent/__init__.py", line 36, in <module>
    from gevent.hub import get_hub, iwait, wait
ImportError: No module named gevent.hub
```

其他第三方库也会出现类似的问题，我之前遇到过。。之前的做法是把thirdparty中的类似`from gevent.hub import get_hub, iwait, wait`的语句手动换为`from thirdparty.gevent.hub import get_hub, iwait, wait`  
再去看看有没有其他解决方法

**Comment by JaySon-Huang** [comment]
#35

**Comment by fooying** [comment]
难道我这边是环境问题，我这边不会出现这样的情况
不过你统一将thirdparty加入sys.path也好，统一处理问题
