### ISSUE TITLE
3102初始化加载插件时错误退出

### ISSUE THREAD

**Issue by ppanger** [fooying/3102#61]
在kali 32bit系统下，按照步骤描述成功安装，但在第一次运行时，到加载插件时出错，出错信息如下：

[*] system init...
'subdomain'
Traceback (most recent call last):
  File "./run3102.py", line 21, in main
    start(args)
  File "/root/3102/core/controllers/controller.py", line 77, in start
    plugin_controller.plugin_init()
  File "/root/3102/core/controllers/plugin_controller.py", line 49, in plugin_init
    self.__register_plugin(plugin)
  File "/root/3102/core/controllers/plugin_controller.py", line 56, in __register_plugin
    kb.plugins[plugin]['name'] = plugin
KeyError: 'subdomain'

这个错误有些令人费解，希望fooying指教，谢谢！

**Comment by flsf** [comment]
你更新一下

**Comment by ppanger** [comment]
重新git clone后问题解决，感谢！
